version: 2.1

orbs:
  node: circleci/node@3.0.1
  cypress: cypress-io/cypress@1.25.1
  aws-ecr: circleci/aws-ecr@6.12.0
  helm: circleci/helm@1.2.0
  shiftleft: shiftleft/shiftleft@1.0.6

workflows:
  build_test_deploy:
    jobs:
      - build
      - deps_audit
      - sast
      - unit_tests:
          requires:
            - build
            - deps_audit
            - sast
      - cypress/run:
          requires:
            - unit_tests
      - aws-ecr/build-and-push-image:
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          context: rp-deploy-secrets
          name: build_push_ecr
          tag: $CIRCLE_SHA1
          repo: react-demo-runner-deploy
          requires:
            - cypress/run
      - hold:
          type: approval
          requires:
            - build_push_ecr
          filters:
            branches:
              only: main
      - deploy_runner:
          requires:
            - hold
jobs:
  build:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: CYPRESS_INSTALL_BINARY=0 npm ci

  deps_audit:
    executor: node
    steps:
      - checkout
      - run: npx audit-ci -c

  sast:
    executor: base
    steps:
      - checkout
      - shiftleft/analyze:
          app: react-demo-runner-deploy
          target: /home/circleci/project/src
          language: js
          cpg: true

  unit_tests:
    parallelism: 2
    executor: node
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: CYPRESS_INSTALL_BINARY=0 npm ci  
      - run:
          name: Test application 
          command: |
            TEST=$(circleci tests glob **/src/**/*.test.js | circleci tests split --split-by=timings)
            npm test $TEST
      - store_test_results:
          path: ~/project/test-results
      - store_artifacts:
          path: ~/project/test-results/junit.xml

  deploy_runner:
    machine: true
    resource_class: ryanpedersen/runner-deploy-demo
    steps:
      - checkout
      - run: aws eks --region ${AWS_REGION} update-kubeconfig --name ${CLUSTER_NAME}
      - helm/upgrade-helm-chart:
          chart: ./helm-charts/react-app-chart
          release-name: react-app-chart
          update-repositories: false
          values-to-override: image.tag=${CIRCLE_SHA1},image.repository=${AWS_CONTAINER_ID}

executors:
  node:
    docker: 
      - image: cimg/node:14.0.0
  base:
    docker:
      - image: cimg/base:stable